# Dependabot will run on day 13 of each month at 02:44 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "44 2 13 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Omega236"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "44 2 13 * *"
    open-pull-requests-limit: 15
    assignees:
      - "Omega236"
